namespace EmbodySense.Web.Models;

/// <summary>Supplies only the client-owned fields accepted by one durable Human Review decision route.</summary>
/// <param name="ExpectedLifecycleVersion">The exact optimistic lifecycle version displayed to the client.</param>
/// <param name="OperationId">The bounded idempotency identity generated by the client.</param>
/// <param name="Detail">Optional bounded detail used only when requesting more information.</param>
public sealed record WebHumanReviewDecisionRequest(int ExpectedLifecycleVersion, string? OperationId, string? Detail);
