namespace EmbodySense.Core.Application.Tests.Verification;

internal static class ApplicationTestIsolationMap
{
    // These classes read or mutate environment, current-directory, current-culture, or process-static state.
    // The verifier contract requires each entry to use ApplicationSerialStateCollection.
    internal const string SerialStateTestClasses = """
    EmbodySense.Core.Application.Tests.Credentials.CredentialLifecycleServiceTests
    EmbodySense.Core.Application.Tests.Credentials.CredentialUseResultTests
    EmbodySense.Core.Application.Tests.Loops.Revisions.GovernedLoopRevisionLifecycleServiceTests
    EmbodySense.Core.Application.Tests.Runtime.ConversationRuntimeStateTests
    EmbodySense.Core.Application.Tests.Runtime.DefaultConversationLoopRunnerTests
    """;

    // Every other current test class uses only per-test instances, immutable shared values, defensive copies,
    // or collision-resistant identifiers. New classes fail verifier admission until explicitly classified.
    internal const string ParallelSafeTestClasses = """
    EmbodySense.Core.Application.Tests.Capabilities.CapabilityAdmissionServiceTests
    EmbodySense.Core.Application.Tests.Capabilities.CapabilityArtifactIntakeServiceTests
    EmbodySense.Core.Application.Tests.Capabilities.CapabilityArtifactManifestValidatorTests
    EmbodySense.Core.Application.Tests.Capabilities.CapabilityCatalogPageTests
    EmbodySense.Core.Application.Tests.Capabilities.CapabilityCatalogServiceTests
    EmbodySense.Core.Application.Tests.Capabilities.CapabilityDependencyResolverTests
    EmbodySense.Core.Application.Tests.Capabilities.CapabilityDependentIndexTests
    EmbodySense.Core.Application.Tests.Capabilities.CapabilityLifecycleCatalogStoreTests
    EmbodySense.Core.Application.Tests.Capabilities.CapabilityLifecycleSelectionServiceTests
    EmbodySense.Core.Application.Tests.Capabilities.CapabilityLifecycleServiceTests
    EmbodySense.Core.Application.Tests.Capabilities.CapabilityPostureServiceTests
    EmbodySense.Core.Application.Tests.CommandActions.CommandActionGraphProjectionContractTests
    EmbodySense.Core.Application.Tests.CommandActions.GovernedCommandActionOperationTests
    EmbodySense.Core.Application.Tests.Context.AgentContextProviderTests
    EmbodySense.Core.Application.Tests.ContextualRoles.ContextualRoleInspectionServiceTests
    EmbodySense.Core.Application.Tests.ContextualRoles.ContextualRoleRevisionPortContractTests
    EmbodySense.Core.Application.Tests.Credentials.CredentialBrokerTests
    EmbodySense.Core.Application.Tests.Credentials.CredentialPortContractTests
    EmbodySense.Core.Application.Tests.Credentials.InMemoryCredentialLifecycleRegistryStoreTests
    EmbodySense.Core.Application.Tests.Governance.Authority.AuthorityPortContractTests
    EmbodySense.Core.Application.Tests.Governance.Authority.Delegation.AuthorityDelegationCompletionTests
    EmbodySense.Core.Application.Tests.Governance.Authority.Delegation.AuthorityDelegationConcurrencyAndFailureTests
    EmbodySense.Core.Application.Tests.Governance.Authority.Delegation.AuthorityDelegationEnvelopeRevalidationTests
    EmbodySense.Core.Application.Tests.Governance.Authority.Delegation.AuthorityDelegationEnvelopeServiceTests
    EmbodySense.Core.Application.Tests.Governance.Authority.Delegation.AuthorityDelegationOriginResolutionTests
    EmbodySense.Core.Application.Tests.Governance.Authority.Delegation.AuthorityDelegationParentLifecycleTests
    EmbodySense.Core.Application.Tests.Governance.Authority.Delegation.AuthorityDelegationTargetResolutionTests
    EmbodySense.Core.Application.Tests.Governance.Authority.Grants.AuthorityGrantDependencySourceTests
    EmbodySense.Core.Application.Tests.Governance.Authority.Grants.AuthorityGrantLifecycleServiceTests
    EmbodySense.Core.Application.Tests.Governance.Authority.Grants.AuthorityGrantMutationContractTests
    EmbodySense.Core.Application.Tests.Governance.Authority.Grants.AuthorityGrantResolverTests
    EmbodySense.Core.Application.Tests.Governance.Authority.Grants.GovernedLoopGrantBindingSourceTests
    EmbodySense.Core.Application.Tests.Governance.Permissions.DirectoryPermissionPolicyTests
    EmbodySense.Core.Application.Tests.Governance.Tools.ToolResultRetentionServiceTests
    EmbodySense.Core.Application.Tests.HumanInput.Continuations.HumanInputResponseContinuationBindingSourceTests
    EmbodySense.Core.Application.Tests.HumanInput.Continuations.HumanInputResponseContinuationServiceTests
    EmbodySense.Core.Application.Tests.HumanInput.Continuations.HumanInputResponseValueProjectorTests
    EmbodySense.Core.Application.Tests.HumanInput.Lifecycle.HumanInputRequestLifecycleAdversarialStoreTests
    EmbodySense.Core.Application.Tests.HumanInput.Lifecycle.HumanInputRequestLifecycleAuthorityTests
    EmbodySense.Core.Application.Tests.HumanInput.Lifecycle.HumanInputRequestLifecycleBlockerRegressionTests
    EmbodySense.Core.Application.Tests.HumanInput.Lifecycle.HumanInputRequestLifecycleCommandTests
    EmbodySense.Core.Application.Tests.HumanInput.Lifecycle.HumanInputRequestLifecycleCreateTests
    EmbodySense.Core.Application.Tests.HumanInput.Lifecycle.HumanInputRequestLifecycleEvidenceCompletenessTests
    EmbodySense.Core.Application.Tests.HumanInput.Lifecycle.HumanInputRequestLifecycleExpectedBindingTests
    EmbodySense.Core.Application.Tests.HumanInput.Lifecycle.HumanInputRequestLifecycleLimitTests
    EmbodySense.Core.Application.Tests.HumanInput.Lifecycle.HumanInputRequestLifecycleLoserReplanTests
    EmbodySense.Core.Application.Tests.HumanInput.Lifecycle.HumanInputRequestLifecyclePrivacyTests
    EmbodySense.Core.Application.Tests.HumanInput.Lifecycle.HumanInputRequestLifecycleReceiptTests
    EmbodySense.Core.Application.Tests.HumanInput.Lifecycle.HumanInputRequestLifecycleRecoveryTests
    EmbodySense.Core.Application.Tests.HumanInput.Lifecycle.HumanInputRequestLifecycleReplayAuthorizationTests
    EmbodySense.Core.Application.Tests.HumanInput.Lifecycle.HumanInputRequestLifecycleReplayProjectionTests
    EmbodySense.Core.Application.Tests.HumanInput.Lifecycle.HumanInputRequestLifecycleStaleDeliveryTests
    EmbodySense.Core.Application.Tests.HumanInput.Lifecycle.HumanInputRequestLifecycleTimingTests
    EmbodySense.Core.Application.Tests.HumanInput.Lifecycle.HumanInputRequestLifecycleTransitionTests
    EmbodySense.Core.Application.Tests.HumanInput.Policies.HumanInputPolicyResolutionServiceTests
    EmbodySense.Core.Application.Tests.HumanInput.Responses.HumanInputResponseLifecycleAdversarialSnapshotTests
    EmbodySense.Core.Application.Tests.HumanInput.Responses.HumanInputResponseLifecycleAuthorityRecoveryTests
    EmbodySense.Core.Application.Tests.HumanInput.Responses.HumanInputResponseLifecycleBoundaryTests
    EmbodySense.Core.Application.Tests.HumanInput.Responses.HumanInputResponseLifecycleContractTests
    EmbodySense.Core.Application.Tests.HumanInput.Responses.HumanInputResponseLifecycleServiceTests
    EmbodySense.Core.Application.Tests.HumanInput.Responses.HumanInputResponseOperationCausalityChronologyTests
    EmbodySense.Core.Application.Tests.HumanReview.CanonicalHumanReviewEffectEvidenceSourceTests
    EmbodySense.Core.Application.Tests.HumanReview.CurrentHumanReviewContinuationAuthoritySourceTests
    EmbodySense.Core.Application.Tests.HumanReview.HumanReviewAdmissionServiceTests
    EmbodySense.Core.Application.Tests.HumanReview.HumanReviewContinuationConsumerTests
    EmbodySense.Core.Application.Tests.HumanReview.HumanReviewContinuationPublicationServiceTests
    EmbodySense.Core.Application.Tests.HumanReview.HumanReviewContinuationRecoveryCoordinatorTests
    EmbodySense.Core.Application.Tests.HumanReview.HumanReviewDecisionActionRecoveryCoordinatorTests
    EmbodySense.Core.Application.Tests.HumanReview.HumanReviewDecisionServiceTests
    EmbodySense.Core.Application.Tests.HumanReview.HumanReviewEffectReleaseReadStatusProjectionTests
    EmbodySense.Core.Application.Tests.Inference.Profiles.GovernedModelAttemptAdmissionServiceTests
    EmbodySense.Core.Application.Tests.Inference.Profiles.GovernedModelRoutingAdmissionServiceTests
    EmbodySense.Core.Application.Tests.Inference.Profiles.GovernedModelUsageReconciliationServiceTests
    EmbodySense.Core.Application.Tests.LocalWorkspace.Actions.GovernedWorkspaceActionOperationTests
    EmbodySense.Core.Application.Tests.LocalWorkspace.CapabilityAuthorityWorkspaceMutationCommitBoundaryTests
    EmbodySense.Core.Application.Tests.Loops.Admission.GovernedLoopAdmissionServiceConsistencyTests
    EmbodySense.Core.Application.Tests.Loops.Admission.GovernedLoopAdmissionServiceRejectionTests
    EmbodySense.Core.Application.Tests.Loops.Admission.GovernedLoopAdmissionServiceTests
    EmbodySense.Core.Application.Tests.Loops.Authoring.CustomLoopAuthoringServiceTests
    EmbodySense.Core.Application.Tests.Loops.Compatibility.GovernedLoopCompatibilityProjectorTests
    EmbodySense.Core.Application.Tests.Loops.CustomLoopRunStoreDefaultsTests
    EmbodySense.Core.Application.Tests.Loops.EffectAuthorityUsage.GovernedLoopEffectAuthorityUsageRequestValidatorTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Authority.GovernedLoopEffectAuthorityBoundaryTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Authority.GovernedLoopFirstBoundRunCompletionBoundaryTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Custom.ConversationPublicationCommitProtocolTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Custom.CustomLoopAdmissionServiceTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Custom.CustomLoopContextResolverTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Custom.CustomLoopConversationRecoveryPolicyTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Custom.CustomLoopLifecycleServiceTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Custom.CustomLoopOrderedRunnerTests
    EmbodySense.Core.Application.Tests.Loops.Execution.DefaultConversationTurnProtocolValidatorTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Effects.GovernedActuatorCatalogResolverTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Effects.GovernedLoopEffectAttemptServiceTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Reconciliation.GovernedLoopEffectReconciliationModelCoherenceTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Reconciliation.GovernedLoopEffectReconciliationModelCopyTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Reconciliation.GovernedLoopEffectReconciliationPortContractTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Reconciliation.GovernedLoopEffectReconciliationProjectionTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Reconciliation.GovernedLoopEffectReconciliationRequestBoundsTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Reconciliation.GovernedLoopEffectReconciliationServiceBoundaryTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Reconciliation.GovernedLoopEffectReconciliationServiceTests
    EmbodySense.Core.Application.Tests.Loops.Execution.Reconciliation.GovernedLoopEffectReconciliationStatusTests
    EmbodySense.Core.Application.Tests.Loops.Failures.GovernedLoopFailureClassificationServiceTests
    EmbodySense.Core.Application.Tests.Loops.Failures.GovernedLoopFailureClassifierTests
    EmbodySense.Core.Application.Tests.Loops.GovernedLoopAdmissionRequestHashTests
    EmbodySense.Core.Application.Tests.Loops.GraphAuthoring.GovernedLoopGraphAuthoringServiceTests
    EmbodySense.Core.Application.Tests.Loops.GraphValidation.GovernedLoopAuthoritySnapshotProviderTests
    EmbodySense.Core.Application.Tests.Loops.GraphValidation.GovernedLoopConditionEvaluatorTests
    EmbodySense.Core.Application.Tests.Loops.GraphValidation.GovernedLoopFailNodeCatalogContractTests
    EmbodySense.Core.Application.Tests.Loops.GraphValidation.GovernedLoopGraphValidationServiceTests
    EmbodySense.Core.Application.Tests.Loops.GraphValidation.GovernedLoopHumanInputNodeCatalogContractTests
    EmbodySense.Core.Application.Tests.Loops.GraphValidation.GovernedLoopHumanReviewNodeCatalogContractTests
    EmbodySense.Core.Application.Tests.Loops.GraphValidation.GovernedLoopPureNodeCatalogContractTests
    EmbodySense.Core.Application.Tests.Loops.GraphValidation.GovernedLoopTopologyNodeCatalogContractTests
    EmbodySense.Core.Application.Tests.Loops.GraphValidation.GovernedLoopWaitNodeCatalogContractTests
    EmbodySense.Core.Application.Tests.Loops.Posture.GovernedLoopOperationalControlServiceTests
    EmbodySense.Core.Application.Tests.Loops.Posture.GovernedLoopOperationalPostureServiceTests
    EmbodySense.Core.Application.Tests.Loops.ReceiptRetention.CustomLoopInvocationReceiptRetentionServiceTests
    EmbodySense.Core.Application.Tests.Loops.ReceiptRetention.CustomLoopReceiptRetentionContractTests
    EmbodySense.Core.Application.Tests.Loops.Retry.GovernedLoopRetryDecisionServiceTests
    EmbodySense.Core.Application.Tests.Loops.Revisions.GovernedLoopRevisionStoreMutationGuardTests
    EmbodySense.Core.Application.Tests.Loops.Sequential.GovernedLoopSequentialAuditOperationIdTests
    EmbodySense.Core.Application.Tests.Loops.Sequential.GovernedLoopSequentialBindingResolverTests
    EmbodySense.Core.Application.Tests.Loops.Sequential.GovernedLoopSequentialFrontierMachineTests
    EmbodySense.Core.Application.Tests.Loops.Sequential.GovernedLoopSequentialInvocationCoordinatorTests
    EmbodySense.Core.Application.Tests.Loops.Sequential.GovernedLoopSequentialLegacyDefinitionProjectorTests
    EmbodySense.Core.Application.Tests.Loops.Sequential.GovernedLoopSequentialPlanBuilderTests
    EmbodySense.Core.Application.Tests.Loops.Sequential.GovernedLoopSequentialResumeExecutorTests
    EmbodySense.Core.Application.Tests.Loops.Sequential.GovernedLoopSequentialRunAnchorAndDispatcherTests
    EmbodySense.Core.Application.Tests.Loops.Sequential.GovernedLoopSequentialRunMaterializerTests
    EmbodySense.Core.Application.Tests.Loops.Sequential.GovernedLoopTopologyPlanBuilderTests
    EmbodySense.Core.Application.Tests.Loops.Sleep.GovernedLoopBackgroundWorkContractTests
    EmbodySense.Core.Application.Tests.Loops.Sleep.GovernedLoopCoordinatorEvidenceContractTests
    EmbodySense.Core.Application.Tests.Loops.Sleep.GovernedLoopCoordinatorRepairServiceTests
    EmbodySense.Core.Application.Tests.Loops.Sleep.GovernedLoopSleepPublicationServiceTests
    EmbodySense.Core.Application.Tests.Loops.Sleep.GovernedLoopWakeRecoveryServiceTests
    EmbodySense.Core.Application.Tests.Loops.Sleep.GovernedLoopWakeServiceTests
    EmbodySense.Core.Application.Tests.Loops.TraceRetention.CustomLoopTraceRetentionServiceTests
    EmbodySense.Core.Application.Tests.Loops.Wait.GovernedLoopWaitContinuationRelayTests
    EmbodySense.Core.Application.Tests.Loops.Wait.GovernedLoopWaitFrontierTests
    EmbodySense.Core.Application.Tests.Runtime.DefaultConversationLoopTurnContractTests
    EmbodySense.Core.Application.Tests.Runtime.RuntimeCommandServiceTests
    EmbodySense.Core.Application.Tests.Runtime.RuntimeDiagnosticFormatterTests
    EmbodySense.Core.Application.Tests.Secrets.Redaction.StructuredRedactionServiceTests
    EmbodySense.Core.Application.Tests.Triggers.Schedules.ScheduleDueOccurrenceEvaluatorTests
    EmbodySense.Core.Application.Tests.Triggers.Schedules.ScheduleMalformedPortEvidenceTests
    EmbodySense.Core.Application.Tests.Triggers.Schedules.ScheduleRecurrenceProofHashTests
    EmbodySense.Core.Application.Tests.Triggers.Schedules.ScheduleTriggerDispatchReadinessServiceTests
    EmbodySense.Core.Application.Tests.Triggers.TriggerClosedBoundaryTests
    EmbodySense.Core.Application.Tests.Triggers.TriggerDeliveryAdmissionServiceTests
    EmbodySense.Core.Application.Tests.Triggers.TriggerQueueAdmissionServiceTests
    EmbodySense.Core.Application.Tests.Triggers.TriggerQueueLifecycleControlServiceTests
    EmbodySense.Core.Application.Tests.Triggers.TriggerWorkerLimitsTests
    EmbodySense.Core.Application.Tests.Triggers.TriggerWorkerServiceTests
    """;
}
