using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace EmbodySense.IntegrationTests.Architecture;

public sealed class AuthoredGlobalTypeGuardTests
{
    [Fact]
    public void Authored_source_files_do_not_declare_types_in_the_global_namespace()
    {
        var repositoryRoot = FindRepositoryRoot();
        var violations = Directory
            .EnumerateFiles(repositoryRoot, "*.cs", SearchOption.AllDirectories)
            .Where(path => !IsBuildOutput(path))
            .Select(path => new SourceFile(path, File.ReadAllText(path)))
            .Where(source => !IsGenerated(source))
            .Where(DeclaresGlobalType)
            .Select(source => Path.GetRelativePath(repositoryRoot, source.Path))
            .OrderBy(path => path, StringComparer.Ordinal)
            .ToArray();

        Assert.True(violations.Length == 0, $"Authored C# files must not declare types in the global namespace:{Environment.NewLine}{string.Join(Environment.NewLine, violations)}");
    }

    [Fact]
    public void Global_type_guard_allows_top_level_programs_and_recognized_generated_sources()
    {
        var sources = new[]
        {
            new SourceFile("Program.cs", "System.Console.WriteLine(\"hello\");"),
            new SourceFile("Generated.g.cs", "// <auto-generated />\ninternal sealed class GeneratedType { }")
        };

        Assert.DoesNotContain(sources, source => !IsGenerated(source) && DeclaresGlobalType(source));
    }

    private static bool DeclaresGlobalType(SourceFile source)
    {
        var root = (CompilationUnitSyntax)CSharpSyntaxTree.ParseText(source.Content).GetRoot();
        return root.Members.Any(member => member is BaseTypeDeclarationSyntax or DelegateDeclarationSyntax);
    }

    private static bool IsBuildOutput(string path)
    {
        var segments = path.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        return segments.Contains("bin", StringComparer.OrdinalIgnoreCase) || segments.Contains("obj", StringComparer.OrdinalIgnoreCase);
    }

    private static bool IsGenerated(SourceFile source)
    {
        var hasGeneratedSuffix = source.Path.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || source.Path.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || source.Path.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase);
        var firstContentLine = source.Content.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries).FirstOrDefault()?.TrimStart();
        var commentContent = firstContentLine?.StartsWith("//", StringComparison.Ordinal) == true
            ? firstContentLine[2..].TrimStart()
            : firstContentLine?.StartsWith("/*", StringComparison.Ordinal) == true
                ? firstContentLine[2..].TrimStart()
                : null;
        return hasGeneratedSuffix && commentContent?.StartsWith("<auto-generated", StringComparison.OrdinalIgnoreCase) == true;
    }

    private static string FindRepositoryRoot()
    {
        var current = new DirectoryInfo(AppContext.BaseDirectory);
        while (current is not null && !File.Exists(Path.Combine(current.FullName, "EmbodySense.sln")))
        {
            current = current.Parent;
        }

        return current?.FullName ?? throw new DirectoryNotFoundException("Could not locate the repository root.");
    }

    private sealed record SourceFile(string Path, string Content);
}
