using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace EmbodySense.IntegrationTests.Architecture;

public sealed class ProductionSourceLayoutTests
{
    [Fact]
    public void Production_source_files_contain_one_matching_top_level_type()
    {
        var root = FindRepositoryRoot();
        var sourceRoot = Path.Combine(root, "src");
        var sources = ProductionProjectRoots(sourceRoot)
            .SelectMany(projectRoot => Directory.EnumerateFiles(projectRoot, "*.cs", SearchOption.AllDirectories))
            .Select(file => new SourceFile(Path.GetRelativePath(root, file), File.ReadAllText(file)));
        var violations = FindViolations(sources);

        Assert.True(violations.Count == 0, string.Join(Environment.NewLine, violations));
    }

    [Fact]
    public void Layout_classification_rejects_filename_multiple_type_and_nested_behavior_violations()
    {
        var sources = new[]
        {
            new SourceFile("Wrong.cs", "namespace Example; internal sealed class Right { }"),
            new SourceFile("Multiple.cs", "namespace Example; internal sealed class Multiple { } internal sealed class Extra { }"),
            new SourceFile("BehaviorHost.cs", "namespace Example; internal sealed class BehaviorHost { private sealed class Worker { public void Run() { } } }"),
            new SourceFile("InitializerHost.cs", "namespace Example; internal sealed class InitializerHost { private sealed class Worker { private readonly object _worker = StartWorker(); } }"),
            new SourceFile("PropertyInitializerHost.cs", "namespace Example; internal sealed class PropertyInitializerHost { private sealed class Worker { private object Value { get; } = StartWorker(); } }"),
            new SourceFile("PublicHost.cs", "namespace Example; internal sealed class PublicHost { public sealed class Visible { } }"),
            new SourceFile("Actors.cs", "namespace Example; public static partial class AuditSchema { public const string Extra = \"extra\"; public static class Actors { } }"),
            new SourceFile("Spoofed.g.cs", "namespace Example; internal sealed class Wrong { } internal sealed class Extra { }\n// <auto-generated />"),
            new SourceFile("InlineSpoof.g.cs", "namespace Example; internal sealed class Wrong { } internal sealed class Extra { } // <auto-generated />")
        };
        var violations = FindViolations(sources);

        Assert.Contains(violations, violation => violation.StartsWith("Wrong.cs:", StringComparison.Ordinal));
        Assert.Contains(violations, violation => violation.StartsWith("Multiple.cs:", StringComparison.Ordinal));
        Assert.Contains(violations, violation => violation.StartsWith("BehaviorHost.cs:", StringComparison.Ordinal));
        Assert.Contains(violations, violation => violation.StartsWith("InitializerHost.cs:", StringComparison.Ordinal));
        Assert.Contains(violations, violation => violation.StartsWith("PropertyInitializerHost.cs:", StringComparison.Ordinal));
        Assert.Contains(violations, violation => violation.StartsWith("PublicHost.cs:", StringComparison.Ordinal));
        Assert.Contains(violations, violation => violation.StartsWith("Actors.cs:", StringComparison.Ordinal));
        Assert.Contains(violations, violation => violation.StartsWith("Spoofed.g.cs:", StringComparison.Ordinal));
        Assert.Contains(violations, violation => violation.StartsWith("InlineSpoof.g.cs:", StringComparison.Ordinal));
    }

    [Fact]
    public void Layout_classification_allows_private_data_generated_files_and_narrow_partial_containers()
    {
        var sources = new[]
        {
            new SourceFile("DataHost.cs", "namespace Example; internal sealed class DataHost { private sealed record Snapshot(string Value); }"),
            new SourceFile("Actors.cs", "namespace Example; public static partial class AuditSchema { public static class Actors { public const string Cli = \"cli\"; } }"),
            new SourceFile("Generated.g.cs", "// <auto-generated />\nnamespace Example; internal sealed class Wrong { } internal sealed class Extra { }"),
            new SourceFile("Program.cs", "System.Console.WriteLine(\"hello\");")
        };

        Assert.Empty(FindViolations(sources));
    }

    private static IReadOnlyList<string> FindViolations(IEnumerable<SourceFile> sources)
    {
        var violations = new List<string>();
        foreach (var source in sources)
        {
            if (IsGenerated(source))
            {
                continue;
            }

            var declarations = CSharpSyntaxTree
                .ParseText(source.Content)
                .GetRoot()
                .DescendantNodes()
                .OfType<BaseTypeDeclarationSyntax>()
                .ToArray();
            if (declarations.Length == 0)
            {
                continue;
            }

            var expectedTypeName = Path.GetFileNameWithoutExtension(source.Path);
            var matchingDeclarations = declarations.Where(declaration => string.Equals(declaration.Identifier.ValueText, expectedTypeName, StringComparison.Ordinal)).ToArray();
            if (matchingDeclarations.Length != 1)
            {
                violations.Add($"{source.Path}: expected exactly one type named `{expectedTypeName}`, found {matchingDeclarations.Length}.");
                continue;
            }

            var owner = matchingDeclarations[0];
            foreach (var declaration in declarations.Where(declaration => declaration != owner))
            {
                if (IsNecessaryPartialAncestor(declaration, owner))
                {
                    continue;
                }

                if (IsPrivateNestedType(declaration) && IsDataOnlyNested(declaration))
                {
                    continue;
                }

                var placement = declaration.Parent is BaseNamespaceDeclarationSyntax or CompilationUnitSyntax ? "additional top-level" : "nested";
                violations.Add($"{source.Path}: {placement} type `{declaration.Identifier.ValueText}` must move to `{declaration.Identifier.ValueText}.cs` unless it is a private data-only model or necessary partial ancestor.");
            }
        }

        return violations;
    }

    private static bool IsGenerated(SourceFile source)
    {
        var hasGeneratedSuffix = source.Path.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || source.Path.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || source.Path.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase);
        var firstContentLine = source.Content.Split(['\r', '\n'], StringSplitOptions.RemoveEmptyEntries).FirstOrDefault()?.TrimStart();
        var commentContent = firstContentLine?.StartsWith("//", StringComparison.Ordinal) == true
            ? firstContentLine[2..].TrimStart()
            : firstContentLine?.StartsWith("/*", StringComparison.Ordinal) == true
                ? firstContentLine[2..].TrimStart()
                : null;
        return hasGeneratedSuffix && commentContent?.StartsWith("<auto-generated", StringComparison.OrdinalIgnoreCase) == true;
    }

    private static bool IsNecessaryPartialAncestor(BaseTypeDeclarationSyntax declaration, BaseTypeDeclarationSyntax owner)
    {
        if (declaration is not TypeDeclarationSyntax partialContainer
            || !partialContainer.Modifiers.Any(modifier => modifier.RawKind == (int)SyntaxKind.PartialKeyword)
            || partialContainer.Modifiers.Any(modifier => !IsPartialContainerModifier(modifier.RawKind))
            || partialContainer.AttributeLists.Count != 0
            || partialContainer.BaseList is not null
            || !owner.Ancestors().OfType<BaseTypeDeclarationSyntax>().Contains(declaration))
        {
            return false;
        }

        return partialContainer.Members.All(member => member is BaseTypeDeclarationSyntax nestedType
            && (nestedType == owner || owner.Ancestors().OfType<BaseTypeDeclarationSyntax>().Contains(nestedType)));
    }

    private static bool IsPartialContainerModifier(int rawKind)
    {
        return rawKind is (int)SyntaxKind.PublicKeyword
            or (int)SyntaxKind.InternalKeyword
            or (int)SyntaxKind.ProtectedKeyword
            or (int)SyntaxKind.PrivateKeyword
            or (int)SyntaxKind.StaticKeyword
            or (int)SyntaxKind.PartialKeyword;
    }

    private static bool IsPrivateNestedType(BaseTypeDeclarationSyntax declaration)
    {
        return declaration.Parent is TypeDeclarationSyntax
            && declaration.Modifiers.Any(modifier => modifier.RawKind == (int)SyntaxKind.PrivateKeyword);
    }

    private static bool IsDataOnlyNested(BaseTypeDeclarationSyntax declaration)
    {
        if (declaration.AttributeLists.Count != 0 || declaration.BaseList is not null)
        {
            return false;
        }

        if (declaration is EnumDeclarationSyntax)
        {
            return true;
        }

        if (declaration is not TypeDeclarationSyntax typeDeclaration
            || typeDeclaration.Modifiers.Any(modifier => modifier.RawKind == (int)SyntaxKind.PartialKeyword))
        {
            return false;
        }

        if (typeDeclaration is RecordDeclarationSyntax recordDeclaration
            && recordDeclaration.ParameterList?.Parameters.Any(parameter => !IsDataOnlyInitializer(parameter.Default, parameter.Type, typeDeclaration.Identifier.ValueText, null)) == true)
        {
            return false;
        }

        var primaryConstructorParameters = PrimaryConstructorParameters(typeDeclaration);
        return typeDeclaration.Members.All(member => member switch
        {
            FieldDeclarationSyntax field => IsDataOnlyField(field, typeDeclaration.Identifier.ValueText, primaryConstructorParameters),
            PropertyDeclarationSyntax property => IsDataOnlyProperty(property, typeDeclaration.Identifier.ValueText, primaryConstructorParameters),
            _ => false
        });
    }

    private static IReadOnlySet<string> PrimaryConstructorParameters(TypeDeclarationSyntax declaration)
    {
        var parameterList = declaration switch
        {
            ClassDeclarationSyntax classDeclaration => classDeclaration.ParameterList,
            StructDeclarationSyntax structDeclaration => structDeclaration.ParameterList,
            RecordDeclarationSyntax recordDeclaration => recordDeclaration.ParameterList,
            _ => null
        };
        return parameterList?.Parameters.Select(parameter => parameter.Identifier.ValueText).ToHashSet(StringComparer.Ordinal)
            ?? new HashSet<string>(StringComparer.Ordinal);
    }

    private static bool IsDataOnlyField(FieldDeclarationSyntax field, string ownerTypeName, IReadOnlySet<string> primaryConstructorParameters)
    {
        var isStatic = field.Modifiers.Any(modifier => modifier.RawKind == (int)SyntaxKind.StaticKeyword);
        var isImmutable = field.Modifiers.Any(modifier => modifier.RawKind is (int)SyntaxKind.ConstKeyword or (int)SyntaxKind.ReadOnlyKeyword);
        return (!isStatic || isImmutable)
            && field.Declaration.Variables.All(variable => IsDataOnlyInitializer(variable.Initializer, field.Declaration.Type, ownerTypeName, primaryConstructorParameters));
    }

    private static bool IsDataOnlyProperty(PropertyDeclarationSyntax property, string ownerTypeName, IReadOnlySet<string> primaryConstructorParameters)
    {
        if (property.ExpressionBody is not null
            || property.AccessorList?.Accessors.Any(accessor => accessor.Body is not null || accessor.ExpressionBody is not null) == true)
        {
            return false;
        }

        var isStatic = property.Modifiers.Any(modifier => modifier.RawKind == (int)SyntaxKind.StaticKeyword);
        var hasMutationAccessor = property.AccessorList?.Accessors.Any(accessor => accessor.RawKind is (int)SyntaxKind.SetAccessorDeclaration or (int)SyntaxKind.InitAccessorDeclaration) == true;
        return (!isStatic || !hasMutationAccessor)
            && IsDataOnlyInitializer(property.Initializer, property.Type, ownerTypeName, primaryConstructorParameters);
    }

    private static bool IsDataOnlyInitializer(EqualsValueClauseSyntax? initializer, TypeSyntax? declaredType, string ownerTypeName, IReadOnlySet<string>? allowedIdentifiers)
    {
        return initializer is null || IsDataOnlyInitializerExpression(initializer.Value, declaredType, ownerTypeName, allowedIdentifiers);
    }

    private static bool IsDataOnlyInitializerExpression(ExpressionSyntax expression, TypeSyntax? declaredType, string ownerTypeName, IReadOnlySet<string>? allowedIdentifiers)
    {
        return expression switch
        {
            LiteralExpressionSyntax => true,
            DefaultExpressionSyntax => true,
            IdentifierNameSyntax identifier => allowedIdentifiers?.Contains(identifier.Identifier.ValueText) == true,
            ParenthesizedExpressionSyntax parenthesized => IsDataOnlyInitializerExpression(parenthesized.Expression, declaredType, ownerTypeName, allowedIdentifiers),
            PrefixUnaryExpressionSyntax unary => IsDataOnlyInitializerExpression(unary.Operand, declaredType, ownerTypeName, allowedIdentifiers),
            ImplicitObjectCreationExpressionSyntax creation => IsSelfConstruction(declaredType, ownerTypeName, creation.ArgumentList?.Arguments, creation.Initializer, allowedIdentifiers),
            ObjectCreationExpressionSyntax creation => IsTypeNamed(creation.Type, ownerTypeName)
                && IsSelfConstruction(declaredType, ownerTypeName, creation.ArgumentList?.Arguments, creation.Initializer, allowedIdentifiers),
            _ => false
        };
    }

    private static bool IsSelfConstruction(TypeSyntax? declaredType, string ownerTypeName, SeparatedSyntaxList<ArgumentSyntax>? arguments, InitializerExpressionSyntax? initializer, IReadOnlySet<string>? allowedIdentifiers)
    {
        return IsTypeNamed(declaredType, ownerTypeName)
            && initializer is null
            && (arguments is null || arguments.Value.All(argument => IsDataOnlyInitializerExpression(argument.Expression, null, ownerTypeName, allowedIdentifiers)));
    }

    private static bool IsTypeNamed(TypeSyntax? type, string expectedName)
    {
        var simpleName = type switch
        {
            IdentifierNameSyntax identifier => identifier.Identifier.ValueText,
            GenericNameSyntax generic => generic.Identifier.ValueText,
            QualifiedNameSyntax qualified => qualified.Right.Identifier.ValueText,
            AliasQualifiedNameSyntax aliasQualified => aliasQualified.Name.Identifier.ValueText,
            NullableTypeSyntax nullable => nullable.ElementType.ToString(),
            _ => null
        };
        return string.Equals(simpleName, expectedName, StringComparison.Ordinal);
    }

    private static IReadOnlyList<string> ProductionProjectRoots(string sourceRoot)
    {
        return Directory
            .EnumerateDirectories(sourceRoot, "EmbodySense.*", SearchOption.TopDirectoryOnly)
            .Where(directory => File.Exists(Path.Combine(directory, $"{Path.GetFileName(directory)}.csproj")))
            .ToArray();
    }

    private static string FindRepositoryRoot()
    {
        var current = new DirectoryInfo(AppContext.BaseDirectory);
        while (current is not null && !File.Exists(Path.Combine(current.FullName, "EmbodySense.sln")))
        {
            current = current.Parent;
        }

        return current?.FullName ?? throw new DirectoryNotFoundException("Could not locate the repository root.");
    }

    private sealed record SourceFile(string Path, string Content);
}
